version: '3.5'

services:
  node:
    container_name: golem_dashboard
    build: .
    restart: always
    environment:
      - REACT_APP_ADDRESSES=192.168.1.2:5000,192.168.1.2:5001
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 3000:3000
